### ISSUE TITLE
Integration fails first initialisation

### ISSUE THREAD

**Issue by MittaAxt** [Ludy87/xplora_watch#347]
### What version of Integration has the issue?

2.10.4

## System Information

version | core-2024.1.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.70-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4972
Installed Version | 1.33.0
Stage | running
Available Repositories | 1365
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 62.3 GB
disk_used | 18.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.1), ESPHome (2023.12.5), TasmoAdmin (0.28.0), Log Viewer (0.16.0), chrony (3.0.0), Mosquitto broker (6.4.0), Samba share (12.2.0), Node-RED (16.0.2), Grafana (9.1.1), RPC Shutdown (2.4), Duck DNS (1.15.0), AirCast (4.0.1), MariaDB (2.6.1), Studio Code Server (5.14.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 29, 2023 at 11:28
-- | --
current_recorder_run | January 5, 2024 at 18:11
estimated_db_size | 249.88 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After a fresh HA installation and adding the integration via HACS, the integration failed to initialize (Failed to setup) after adding the mobile number and password for the first time and no device is shown

Trying to "Configure" the integration afterwards opens the window with the correct information of the watch, but the integration fails again after clicking save, and the device list is still empty.

### Reproduction steps

1. Add integration via HACS
2. Restart HA
3. try to configure xplora integration for the first time
4. Enter mobile number and password
5. wait
-> Failed to setup

### Debug logs

```text
2024-01-05 21:58:15.325 DEBUG (MainThread) [custom_components.xplora_watch] Configure based on config entry feb9749d4edff9261188897b1d3fec36
2024-01-05 21:58:15.652 DEBUG (MainThread) [custom_components.xplora_watch] pyxplora_api lib version: 2.10.0-1298
2024-01-05 21:58:17.024 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Fetch data from Xplora: 9298082
2024-01-05 21:58:18.969 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] load address from openstreetmap.org
2024-01-05 21:58:18.970 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Manually updated xplora_watch-47046 data
2024-01-05 21:58:18.970 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Finished fetching xplora_watch-47046 data in 3.317 seconds (success: True)
2024-01-05 21:58:20.173 DEBUG (MainThread) [custom_components.xplora_watch.helper] set services.yaml path: /config/custom_components/xplora_watch/services.yaml
2024-01-05 21:58:20.173 DEBUG (MainThread) [custom_components.xplora_watch.helper] services_en.json path: /config/custom_components/xplora_watch/jsons/service_en.json
2024-01-05 21:58:20.174 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Xplora® for xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xplora_watch/__init__.py", line 64, in async_setup_entry
    await create_service_yaml_file(hass, entry, watches)
  File "/config/custom_components/xplora_watch/helper.py", line 125, in create_service_yaml_file
    yaml_service.get("see", None)
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by MittaAxt** [comment]
Tested today after the update to 2.12.1 but still failing the initialisation

`2024-01-08 10:54:31.407 DEBUG (MainThread) [custom_components.xplora_watch] Configure based on config entry de6dc2d6a354072e61f79b3589ba7e1a
2024-01-08 10:54:31.565 DEBUG (MainThread) [custom_components.xplora_watch] pyxplora_api lib version: 2.10.0-1298
2024-01-08 10:54:32.979 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Fetch data from Xplora: 9298082
2024-01-08 10:54:34.904 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] load address from openstreetmap.org
2024-01-08 10:54:34.905 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Manually updated xplora_watch-47046 data
2024-01-08 10:54:34.905 DEBUG (MainThread) [custom_components.xplora_watch.coordinator] Finished fetching xplora_watch-47046 data in 3.340 seconds (success: True)
2024-01-08 10:54:36.133 DEBUG (MainThread) [custom_components.xplora_watch.helper] set services.yaml path: /config/custom_components/xplora_watch/services.yaml
2024-01-08 10:54:36.133 DEBUG (MainThread) [custom_components.xplora_watch.helper] services_en.json path: /config/custom_components/xplora_watch/jsons/service_en.json
2024-01-08 10:54:36.134 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Xplora® for xplora_watch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xplora_watch/__init__.py", line 64, in async_setup_entry
    await create_service_yaml_file(hass, entry, watches)
  File "/config/custom_components/xplora_watch/helper.py", line 125, in create_service_yaml_file
    yaml_service.get("see", None)
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute ''`

**Comment by Ludy87** [comment]
Hi, your integration is not loaded correctly, it shows the wrong lib version ```pyxplora_api lib version: 2.10.0-1298```

**Comment by MittaAxt** [comment]
hm ok i was already wondering about that 
that mismatchbetween what I saw in my UI(installed 2.12.1, while 2.10.0 is reported) seems to be related to the point that 2.12.1 requires 2024.1.2 while I have just 2024.1.1 installed when I updated to 2.12.1

**Comment by MittaAxt** [comment]
can confirm 2024.1.2 and 2.12.1 fixed the issue

**Comment by distante** [comment]
> you can also simply update the files in the xplora_watch folder, i.e. not via HACS

Do we have to do something manually?

I am on the lastest HA and Xplora integration and I still see this error after HA reboot.

```
Logger: homeassistant.components.notify
Source: helpers/entity_platform.py:361
integration: Notifications (documentation, issues)
First occurred: 07:29:23 (1 occurrences)
Last logged: 07:29:23

Error while setting up xplora_watch platform for notify: module 'custom_components.xplora_watch.notify' has no attribute 'async_setup_entry'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    awaitable = async_create_setup_awaitable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 329, in async_create_setup_awaitable
    return platform.async_setup_entry(  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'custom_components.xplora_watch.notify' has no attribute 'async_setup_entry'
```


- Integration `v2.14.2`
- HA :
```
Core 2025.2.0
Supervisor 2025.02.0
Operating System 14.2
Frontend 20250205.0
```
